"""add_login_sessions_table

Revision ID: 863552bac770
Revises: 001_initial
Create Date: 2026-06-13 23:18:58.318620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '863552bac770'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('browser_profile_id', sa.UUID(), nullable=True),
    sa.Column('monitoring_account_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='loginsessionstatus'), nullable=False),
    sa.Column('vnc_url', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['browser_profile_id'], ['browser_profiles.id'], ),
    sa.ForeignKeyConstraint(['monitoring_account_id'], ['monitoring_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('artifacts', 'artifact_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SCREENSHOT', 'HTML', 'RAW_PAYLOAD', 'ERROR_TRACE', name='artifacttype', native_enum=False, length=20),
               existing_nullable=False)
    op.drop_index('ix_tweets_author_username', table_name='tweets')
    op.drop_index('ix_tweets_posted_at', table_name='tweets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tweets_posted_at', 'tweets', ['posted_at'], unique=False)
    op.create_index('ix_tweets_author_username', 'tweets', ['author_username'], unique=False)
    op.alter_column('artifacts', 'artifact_type',
               existing_type=sa.Enum('SCREENSHOT', 'HTML', 'RAW_PAYLOAD', 'ERROR_TRACE', name='artifacttype', native_enum=False, length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table('login_sessions')
    # ### end Alembic commands ###
